#!/usr/bin/env python3
"""Validate every research record against docs/research/schema.yaml, and keep the README
inventory generated from the records instead of written beside them.

Research records are YAML with a fixed schema: enum keys instead of free text wherever a
value is one of a known set, required fields that answer the questions CONTRACT.md asks,
and rules the schema cannot express (file naming, commit references, validation authority,
what may be tracked). A record that breaks any of them is an error here, in the test suite,
and in CI — the contract is checked, not only written down.

  python tools/maintain/check_research.py              # report problems; exit 1 on errors
  python tools/maintain/check_research.py --strict     # warnings count as errors (release)
  python tools/maintain/check_research.py --git        # also check every commit exists
  python tools/maintain/check_research.py --drafts     # also validate docs/research-drafts/
  python tools/maintain/check_research.py --write-inventory   # regenerate the README table
                                                               # and docs/research/questions.md

PyYAML is a development dependency (requirements-dev.txt), never a runtime one: research
records are not runtime input, so the runtime stays stdlib-only (tests/checks/deps.py).
"""
from __future__ import annotations

import argparse
import datetime as _dt
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # a development tool; the runtime never imports it
    yaml = None

REPO_ROOT = Path(__file__).resolve().parents[2]
RESEARCH = REPO_ROOT / "docs" / "research"
DRAFTS = REPO_ROOT / "docs" / "research-drafts"
SCHEMA = RESEARCH / "schema.yaml"
README = RESEARCH / "README.md"
QUESTIONS = RESEARCH / "questions.md"
QUESTIONS_BEGIN = "<!-- research-questions:begin (generated by tools/maintain/check_research.py --write-inventory) -->"
QUESTIONS_END = "<!-- research-questions:end -->"
INVENTORY_BEGIN = "<!-- research-inventory:begin (generated by tools/maintain/check_research.py --write-inventory) -->"
INVENTORY_END = "<!-- research-inventory:end -->"

# Record IDs are PREFIX-NNN; a research question is RQ-NN with an optional lowercase letter
# (RQ-07a), the numbering questions.md used before questions became records (DEC-017).
_ID_SHAPE = r"[A-Z]+-\d{2,3}[a-z]?"
_ID = re.compile(r"^(?P<prefix>[A-Z]+)-(?P<num>\d{2,3}[a-z]?)$")
_FILE = re.compile(rf"^(?P<id>{_ID_SHAPE})-(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)\.yaml$")
_NUM = {"RQ": re.compile(r"^\d{2}[a-z]?$")}
_NUM_DEFAULT = re.compile(r"^\d{3}$")
# Version 1 is the frozen format of records tracked before DEC-017; RQ never had it.
LEGACY_VERSION = 1
# Types that must name the research question(s) they serve from version 2 on.
QUESTIONED = ("DEC", "H", "EXP", "CASE", "SYN")
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_COMMIT = re.compile(r"^[0-9a-f]{7,40}$")
UNCOMMITTED = "uncommitted"
TEMPLATE = "_TEMPLATE.yaml"
_EVALUATED = {"validated", "partially_validated", "rejected"}


class Report:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, where: str, message: str) -> None:
        self.errors.append(f"{where}: {message}")

    def warn(self, where: str, message: str) -> None:
        self.warnings.append(f"{where}: {message}")


def load_schema() -> dict:
    return yaml.safe_load(SCHEMA.read_text(encoding="utf-8"))


def _resolve(spec: dict, schema: dict) -> dict:
    if "$ref" in spec:
        return schema["blocks"][spec["$ref"]]
    return spec


def _id_match(value: object):
    """The ID's match when its number has the shape its prefix uses, else None."""
    match = _ID.match(value) if isinstance(value, str) else None
    if match and (_NUM.get(match["prefix"]) or _NUM_DEFAULT).match(match["num"]):
        return match
    return None


def _check_value(value, spec: dict, schema: dict, where: str, report: Report, found: dict) -> None:
    """One value against one field spec. Collects ids and commits into `found`."""
    spec = _resolve(spec, schema)
    kind = spec["type"]
    if kind in ("str", "text"):
        if not isinstance(value, str) or not value.strip():
            report.error(where, f"must be a non-empty string ({kind})")
        elif kind == "str" and "\n" in value.strip():
            report.error(where, "must be one line (use a `text` field for prose)")
    elif kind == "date":
        # PyYAML reads an unquoted YYYY-MM-DD as a date already.
        if isinstance(value, _dt.date):
            return
        if not (isinstance(value, str) and _DATE.match(value)):
            report.error(where, "must be a date, YYYY-MM-DD")
    elif kind == "int":
        if not isinstance(value, int) or isinstance(value, bool):
            report.error(where, "must be an integer")
    elif kind == "bool":
        if not isinstance(value, bool):
            report.error(where, "must be true or false")
    elif kind == "enum":
        allowed = schema["enums"][spec["enum"]]
        if value not in allowed:
            report.error(where, f"'{value}' not in {spec['enum']}: {', '.join(allowed)}")
    elif kind == "id":
        match = _id_match(value)
        if not match:
            report.error(where, f"'{value}' is not a record ID (PREFIX-NNN, or RQ-NN)")
        elif match["prefix"] not in spec.get("ids", []):
            report.error(where, f"'{value}' must reference one of: {', '.join(spec['ids'])}")
        else:
            found.setdefault("ids", []).append((where, value))
    elif kind == "commit":
        if value == UNCOMMITTED:
            found.setdefault("uncommitted", []).append(where)
        elif not (isinstance(value, str) and _COMMIT.match(value)):
            report.error(where, f"'{value}' is not a commit hash (7..40 lowercase hex) or `{UNCOMMITTED}`")
        else:
            found.setdefault("commits", []).append((where, value))
    elif kind == "list":
        if not isinstance(value, list):
            report.error(where, "must be a list")
            return
        if len(value) < int(spec.get("min_items", 0)):
            report.error(where, f"needs at least {spec['min_items']} item(s)")
        for index, item in enumerate(value):
            _check_value(item, spec["items"], schema, f"{where}[{index}]", report, found)
    elif kind == "map":
        _check_map(value, spec["fields"], schema, where, report, found)
    else:  # a schema error, not a record error
        report.error(where, f"schema names unknown type '{kind}'")


def _check_map(value, fields: dict, schema: dict, where: str, report: Report, found: dict) -> None:
    if not isinstance(value, dict):
        report.error(where, "must be a mapping")
        return
    for key in value:
        if key not in fields:
            report.error(f"{where}.{key}" if where else str(key), f"unknown key; allowed: {', '.join(fields)}")
    for key, raw_spec in fields.items():
        spec = _resolve(raw_spec, schema)
        path = f"{where}.{key}" if where else key
        if key not in value or value[key] is None:
            if spec.get("required", True):
                report.error(path, "required")
            continue
        _check_value(value[key], raw_spec, schema, path, report, found)


def _get(record: dict, dotted: str):
    node = record
    for part in dotted.split("."):
        if not isinstance(node, dict):
            return None
        node = node.get(part)
    return node


def _walk_keys(node, path: str = ""):
    if isinstance(node, dict):
        for key, child in node.items():
            here = f"{path}.{key}" if path else str(key)
            yield here, key
            yield from _walk_keys(child, here)
    elif isinstance(node, list):
        for index, child in enumerate(node):
            yield from _walk_keys(child, f"{path}[{index}]")


def check_record(path: Path, schema: dict, report: Report, *, tracked: bool) -> dict | None:
    rel = path.relative_to(REPO_ROOT).as_posix()
    name = path.name
    match = _FILE.match(name)
    if not match or not _id_match(match["id"]):
        report.error(rel, "file name must be `<PREFIX-NNN>-<kebab-slug>.yaml` (`RQ-NN` for a question)")
        return None
    try:
        record = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        report.error(rel, f"not valid YAML: {exc}")
        return None
    if not isinstance(record, dict):
        report.error(rel, "top level must be a mapping")
        return None
    prefix = match["id"].split("-")[0]
    type_spec = schema["types"].get(prefix)
    if type_spec is None:
        report.error(rel, f"unknown record prefix '{prefix}'")
        return None
    if path.parent.name != type_spec["directory"]:
        report.error(rel, f"{prefix} records live in {type_spec['directory']}/")
    found: dict = {}
    _check_map(record, type_spec["fields"], schema, "", _Scoped(report, rel), found)
    if record.get("id") != match["id"]:
        report.error(rel, f"id '{record.get('id')}' does not match the file name ({match['id']})")
    version = record.get("schema_version")
    current = schema["schema_version"]
    if tracked and prefix != "RQ" and version == LEGACY_VERSION:
        pass  # frozen before DEC-017 (CONTRACT.md §15); it keeps the format it was tracked in
    elif version != current:
        report.error(rel, f"schema_version must be {current}")
    if prefix in QUESTIONED and version == current and not record.get("questions"):
        report.error(rel, "questions: name the research question(s) this record serves (RQ-NN, CONTRACT.md §16)")
    if prefix == "RQ" and record.get("status") == "answered" and not record.get("records"):
        report.error(rel, "an answered question lists at least one tracked record under records")

    # H and EXP are external to the code: no commit anywhere in them.
    if prefix in ("H", "EXP"):
        for where, key in _walk_keys(record):
            if key in ("commit", "commits"):
                report.error(rel, f"{where}: {prefix} records carry no commit reference")

    disposition = record.get("disposition") or {}
    impl = disposition.get("implementation_status")
    validation = disposition.get("validation_status")
    if prefix == "DEC" and impl in ("implemented", "partially_implemented"):
        commits = _get(record, "implementation.commits") or []
        if not commits:
            report.error(rel, "an implemented decision names the commit(s) that implement it")
    for where in found.get("uncommitted", []):
        report.warn(rel, f"{where}: `{UNCOMMITTED}` — replace with the commit hash once committed")
    if validation not in (None, "not_validated", "observed"):
        if not disposition.get("validated_by") or not disposition.get("validated_on"):
            report.error(rel, f"validation_status {validation} needs validated_by and validated_on (maintainer only)")
    if validation in _EVALUATED:
        if prefix == "DEC":
            runs = _get(record, "validation.runs") or []
            if not any(isinstance(run, dict) and run.get("clean") is True for run in runs):
                report.error(rel, f"a DEC is {validation} only on a named clean direct-use run (validation.runs, clean: true)")
        elif prefix == "EXP":
            if record.get("status") != "completed" or not record.get("results"):
                report.error(rel, f"an EXP is {validation} only once completed with results")
        else:
            refs = [value for _, value in found.get("ids", []) if value.startswith("EXP-")]
            if not refs:
                report.error(rel, f"validation_status {validation} needs an evaluation: reference the EXP that measured it")
    if tracked:
        for dotted, allowed in (type_spec.get("tracked_when") or {}).items():
            if _get(record, dotted) not in allowed:
                report.error(
                    rel,
                    f"tracked records need {dotted} in {allowed} (carried out, with a result); "
                    "otherwise it belongs in docs/research-drafts/ (CONTRACT.md §15)",
                )
    return {"id": match["id"], "path": path, "record": record, "found": found, "rel": rel}


class _Scoped:
    """Prefix every message with the record's path."""

    def __init__(self, report: Report, rel: str) -> None:
        self._report, self._rel = report, rel

    def error(self, where: str, message: str) -> None:
        self._report.error(self._rel, f"{where}: {message}" if where else message)

    def warn(self, where: str, message: str) -> None:
        self._report.warn(self._rel, f"{where}: {message}" if where else message)


def _files(root: Path, schema: dict) -> list[Path]:
    out: list[Path] = []
    for type_spec in schema["types"].values():
        directory = root / type_spec["directory"]
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if path.is_file() and path.name != TEMPLATE and path.suffix in (".yaml", ".yml", ".md"):
                out.append(path)
    return out


def _stray_markdown(paths: list[Path], report: Report) -> list[Path]:
    kept: list[Path] = []
    for path in paths:
        if path.suffix == ".md":
            report.error(path.relative_to(REPO_ROOT).as_posix(), "research records are YAML since schema_version 1; convert it (CONTRACT.md §16)")
        else:
            kept.append(path)
    return kept


def _git_has(commit: str) -> bool:
    try:
        done = subprocess.run(
            ["git", "cat-file", "-e", f"{commit}^{{commit}}"],
            cwd=REPO_ROOT, capture_output=True, timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return done.returncode == 0


def _check_question_links(records: dict[str, dict], tracked: dict[str, dict], report: Report) -> None:
    """An RQ and the records serving it name each other.

    An RQ's `records` are tracked records only — a draft is git-ignored and absent from a
    clean clone — so a tracked RQ never depends on a draft. A version-2 record lists its RQs
    under `questions`; a listed record names the RQ back, and a tracked record's RQ lists it.
    Version-1 records are frozen without `questions` and are linked from the RQ side only.
    """
    for record_id, entry in records.items():
        record = entry["record"]
        if record_id.startswith("RQ-"):
            for index, listed in enumerate(record.get("records") or []):
                target = tracked.get(str(listed))
                if target is None:
                    report.error(entry["rel"], f"records[{index}]: {listed} is not a tracked record; name drafts in notes as plain text")
                    continue
                named = target["record"].get("questions") or []
                if target["record"].get("schema_version") != LEGACY_VERSION and record_id not in named:
                    report.error(entry["rel"], f"records lists {listed}, whose questions do not name {record_id}")
        else:
            for question in record.get("questions") or []:
                target = records.get(str(question))
                if target is None:
                    continue  # the reference check reports an RQ that resolves nowhere
                if record_id in tracked and record_id not in (target["record"].get("records") or []):
                    report.error(entry["rel"], f"questions names {question}, whose records do not list {record_id}")


def _check_reciprocal_links(records: dict[str, dict], report: Report) -> None:
    """H and EXP name each other: an EXP's `hypothesis` lists it back under the H's
    `experiments`, and every EXP an H lists names that H. Checked wherever both records are
    present; a link to a record that is not here is the reference check's to report."""
    for record_id, entry in records.items():
        record = entry["record"]
        if record_id.startswith("EXP-"):
            hypothesis = record.get("hypothesis")
            target = records.get(str(hypothesis))
            if target is not None and record_id not in (target["record"].get("experiments") or []):
                report.error(entry["rel"], f"hypothesis {hypothesis} does not list {record_id} under experiments")
        elif record_id.startswith("H-"):
            for experiment in record.get("experiments") or []:
                target = records.get(str(experiment))
                if target is not None and target["record"].get("hypothesis") != record_id:
                    report.error(
                        entry["rel"],
                        f"experiments lists {experiment}, whose hypothesis is {target['record'].get('hypothesis')}, not {record_id}",
                    )


def validate(*, strict: bool = False, git: bool = False, drafts: bool = False) -> Report:
    report = Report()
    schema = load_schema()
    records: dict[str, dict] = {}
    for path in _stray_markdown(_files(RESEARCH, schema), report):
        entry = check_record(path, schema, report, tracked=True)
        if entry is None:
            continue
        if entry["id"] in records:
            report.error(entry["rel"], f"duplicate id {entry['id']} (also {records[entry['id']]['rel']})")
        records[entry["id"]] = entry
    draft_ids: set[str] = set()
    draft_records: dict[str, dict] = {}
    if DRAFTS.is_dir():
        for path in _files(DRAFTS, schema):
            name = _FILE.match(path.name) or re.match(rf"^(?P<id>{_ID_SHAPE})", path.name)
            if name:
                draft_ids.add(name["id"])
                if name["id"] in records:
                    report.error(path.relative_to(REPO_ROOT).as_posix(), f"duplicate id {name['id']}: also tracked as {records[name['id']]['rel']}")
            if not drafts:
                continue
            if path.suffix == ".md":
                report.error(path.relative_to(REPO_ROOT).as_posix(), "drafts are YAML too; convert it from the type's _TEMPLATE.yaml (CONTRACT.md §16)")
                continue
            entry = check_record(path, schema, report, tracked=False)
            if entry is not None:
                draft_records[entry["id"]] = entry
    _check_reciprocal_links({**draft_records, **records}, report)
    _check_question_links({**draft_records, **records}, records, report)
    for entry in records.values():
        for where, ref in entry["found"].get("ids", []):
            if ref == entry["id"] or ref in records:
                continue
            if ref in draft_ids:
                continue
            message = f"{where}: references {ref}, which is neither tracked nor a known draft"
            (report.error if DRAFTS.is_dir() else report.warn)(entry["rel"], message)
        if git:
            for where, commit in entry["found"].get("commits", []):
                if not _git_has(commit):
                    report.error(entry["rel"], f"{where}: commit {commit} is not in this repository")
    for path in (RESEARCH / type_spec["directory"] / TEMPLATE for type_spec in schema["types"].values()):
        if not path.is_file():
            report.error(path.relative_to(REPO_ROOT).as_posix(), "missing template")
    if strict:
        report.errors.extend(f"(strict) {w}" for w in report.warnings)
        report.warnings = []
    report.records = records  # type: ignore[attr-defined]
    return report


def inventory(records: dict[str, dict]) -> str:
    order = {prefix: index for index, prefix in enumerate(("CASE", "DEC", "EXP", "H", "SYN", "ARC", "LIT"))}

    def key(item):
        prefix, num = item[0].split("-")
        return order.get(prefix, 99), int(num)

    lines = [
        INVENTORY_BEGIN,
        "| ID | Title | Type status | Implementation | Validation | Commit |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for record_id, entry in sorted(((i, e) for i, e in records.items() if not i.startswith("RQ-")), key=key):
        record = entry["record"]
        disposition = record.get("disposition") or {}
        status = record.get("status") or record.get("outcome") or "—"
        commits = _get(record, "implementation.commits") or []
        link = entry["path"].relative_to(RESEARCH).as_posix()
        title = str(record.get("title") or "").replace("|", "\\|")
        lines.append(
            f"| [{record_id}]({link}) | {title} | {status} | {disposition.get('implementation_status')} | "
            f"{disposition.get('validation_status')} | {', '.join(str(c) if c == UNCOMMITTED else str(c)[:7] for c in commits) or '—'} |"
        )
    lines.append(INVENTORY_END)
    return "\n".join(lines)


def _one_line(text: object) -> str:
    return " ".join(str(text or "").split()).replace("|", "\\|")


def questions_index(records: dict[str, dict]) -> str:
    """The questions.md table, generated from the RQ records."""

    def key(item):
        num = _ID.match(item[0])["num"]
        return int(num[:2]), num[2:]

    lines = [
        QUESTIONS_BEGIN,
        "| ID | Question | What exists today | Status | Records |",
        "| --- | --- | --- | --- | --- |",
    ]
    for record_id, entry in sorted(((i, e) for i, e in records.items() if i.startswith("RQ-")), key=key):
        record = entry["record"]
        link = entry["path"].relative_to(RESEARCH).as_posix()
        listed = []
        for ref in record.get("records") or []:
            target = records.get(str(ref))
            listed.append(f"[{ref}]({target['path'].relative_to(RESEARCH).as_posix()})" if target else str(ref))
        lines.append(
            f"| [{record_id}]({link}) | {_one_line(record.get('question'))} | {_one_line(record.get('what_exists'))} | "
            f"{record.get('status')} | {', '.join(listed) or '—'} |"
        )
    lines.append(QUESTIONS_END)
    return "\n".join(lines)


def _with_block(path: Path, begin: str, end_marker: str, block: str) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    start, end = text.find(begin), text.find(end_marker)
    if start < 0 or end < 0:
        return text, text
    return text, text[:start] + block + text[end + len(end_marker):]


def _readme_with(table: str) -> tuple[str, str]:
    return _with_block(README, INVENTORY_BEGIN, INVENTORY_END, table)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--strict", action="store_true", help="warnings are errors (use for a release)")
    parser.add_argument("--git", action="store_true", help="check that every commit hash exists")
    parser.add_argument("--drafts", action="store_true", help="also validate docs/research-drafts/ (not tracked-gated)")
    parser.add_argument("--write-inventory", action="store_true", help="regenerate the README inventory table")
    args = parser.parse_args(argv)
    if yaml is None:
        print("[check_research] PyYAML missing: pip install -r requirements-dev.txt", file=sys.stderr)
        return 2
    report = validate(strict=args.strict, git=args.git, drafts=args.drafts)
    generated = (
        (README, "README inventory", INVENTORY_BEGIN, INVENTORY_END, inventory(report.records)),  # type: ignore[attr-defined]
        (QUESTIONS, "questions index", QUESTIONS_BEGIN, QUESTIONS_END, questions_index(report.records)),  # type: ignore[attr-defined]
    )
    for path, label, begin, end_marker, block in generated:
        rel = path.relative_to(REPO_ROOT).as_posix()
        current, wanted = _with_block(path, begin, end_marker, block)
        if begin not in current:
            report.error(rel, f"{label} markers missing")
        elif current != wanted:
            if args.write_inventory:
                path.write_text(wanted, encoding="utf-8", newline="\n")
                print(f"[check_research] {label} regenerated")
            else:
                report.error(rel, f"{label} is stale; run with --write-inventory")
    for warning in report.warnings:
        print(f"WARN  {warning}")
    for error in report.errors:
        print(f"ERROR {error}")
    count = len(report.records)  # type: ignore[attr-defined]
    if report.errors:
        print(f"[check_research] {len(report.errors)} error(s) in {count} record(s)")
        return 1
    print(f"[check_research] OK — {count} record(s), {len(report.warnings)} warning(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
