ROLE_EXPLORATION = "exploration"
ROLE_REASONING = "reasoning"
ROLE_EXECUTION = "execution"
ROLE_VERIFICATION = "verification"

VALID_ROLES = {ROLE_EXPLORATION, ROLE_REASONING, ROLE_EXECUTION, ROLE_VERIFICATION}
