ROLE_EXPLORATION = "exploration"
ROLE_REASONING = "reasoning"

MODEL_KIMI = "kimi"
MODEL_CLAUDE = "claude"

MODEL_ROLES = {
    MODEL_KIMI: ROLE_EXPLORATION,
    MODEL_CLAUDE: ROLE_REASONING,
}

VALID_ROLES = {ROLE_EXPLORATION, ROLE_REASONING}
VALID_MODELS = {MODEL_KIMI, MODEL_CLAUDE}
